#include <memory>
#include <vector>
#include <string>
#include <ostream>
#include <istream>
#include <iterator>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <stdexcept>
#include <cstdlib>
#include <ctime>
#include <numeric>
#include <cmath>
#include "Action.hpp"
#include "AI.hpp"
#include "ArmorCapacity.hpp"
#include "Army.hpp"
#include "battle.hpp"
#include "Capacity.hpp"
#include "Comparator.hpp"
#include "DamageCapacity.hpp"
#include "EmptyAction.hpp"
#include "EscapeAction.hpp"
#include "Extractor.hpp"
#include "FirerateCapacity.hpp"
#include "LifeCapacity.hpp"
#include "MoveAction.hpp"
#include "Point.hpp"
#include "RangeCapacity.hpp"
#include "RegenCapacity.hpp"
#include "SpeedCapacity.hpp"
#include "training.hpp"
#include "Tree.hpp"
#include "Unit.hpp"
